<?php

use CodeIgniter\Router\RouteCollection;

/** @var RouteCollection $routes */
$routes->setDefaultNamespace('App\Controllers');
$routes->setDefaultController('AppPageController');
$routes->setDefaultMethod('dashboard');
$routes->setTranslateURIDashes(false);
$routes->set404Override();
$routes->setAutoRoute(false);

$routes->get('/', 'AppPageController::dashboard');
$routes->get('login', 'LoginController::show');
$routes->get('login.html', 'LoginController::show');

$routes->group('api', ['namespace' => 'App\Controllers\Api'], static function ($routes) {
    $routes->post('auth/login', 'AuthController::login');
    $routes->get('invitation/(:segment)', 'AuthController::invitation/$1');
    $routes->post('invitation/(:segment)/accept', 'AuthController::acceptInvitation/$1');
    $routes->get('tenants', 'AuthController::tenants');
    $routes->get('tenant/(:segment)', 'AuthController::tenant/$1');
    $routes->get('public/order/bootstrap', 'PublicOrderController::bootstrap');
    $routes->get('public/order/member', 'PublicOrderController::member');
    $routes->post('public/order', 'PublicOrderController::submit');
    $routes->post('webhook/xendit', 'SalesController::xenditWebhook');
    $routes->get('public/card-payment/(:segment)', 'SalesController::publicCardPayment/$1');
    $routes->post('public/card-payment/(:segment)/sync', 'SalesController::syncPublicCardPayment/$1');
});
$routes->group('api/page', static function ($routes) {
    $routes->get('login/bootstrap', 'LoginController::bootstrap');
    $routes->post('login/submit', 'LoginController::submit');
    $routes->get('order/bootstrap', 'OnlineOrderController::bootstrap');
    $routes->get('order/member', 'OnlineOrderController::member');
    $routes->post('order/submit', 'OnlineOrderController::submit');
});
$routes->get('payment/card/(:segment)', 'AppPageController::cardPayment/$1');
$routes->get('invitation/(:segment)', 'AppPageController::invitation/$1');
$routes->get('order', 'OnlineOrderController::show');

$routes->group('api', ['namespace' => 'App\Controllers\Api', 'filter' => 'jwt-auth'], static function ($routes) {
    $routes->get('company', 'AccessController::listCompanies');
    $routes->get('company/(:segment)', 'AccessController::getCompany/$1');
    $routes->post('company', 'AccessController::company');
    $routes->put('company/(:segment)', 'AccessController::updateCompany/$1');
    $routes->delete('company/(:segment)', 'AccessController::deleteCompany/$1');
    $routes->post('company/(:segment)/invite-admin', 'AccessController::resendCompanyAdminInvitation/$1');
    $routes->post('company-logo', 'AccessController::uploadLogo');
    $routes->get('outlet', 'AccessController::listOutlets');
    $routes->get('outlet/(:segment)', 'AccessController::getOutlet/$1');
    $routes->post('outlet', 'AccessController::outlet');
    $routes->put('outlet/(:segment)', 'AccessController::updateOutlet/$1');
    $routes->delete('outlet/(:segment)', 'AccessController::deleteOutlet/$1');
    $routes->get('role', 'AccessController::listRoles');
    $routes->get('role/(:segment)', 'AccessController::getRole/$1');
    $routes->post('role', 'AccessController::role');
    $routes->put('role/(:segment)', 'AccessController::updateRole/$1');
    $routes->delete('role/(:segment)', 'AccessController::deleteRole/$1');
    $routes->get('user', 'AccessController::listUsers');
    $routes->get('user/(:segment)', 'AccessController::getUser/$1');
    $routes->post('user', 'AccessController::user');
    $routes->put('user/(:segment)', 'AccessController::updateUser/$1');
    $routes->post('user/(:segment)/invite', 'AccessController::resendUserInvitation/$1');
    $routes->delete('user/(:segment)', 'AccessController::deleteUser/$1');
    $routes->get('dashboard', 'DashboardController::show');
    $routes->get('onboarding', 'OnboardingController::show');
    $routes->get('page/pos/bootstrap', '\App\Controllers\PosController::bootstrap');
    $routes->get('page/settings/bootstrap', '\App\Controllers\SettingsPageController::bootstrap');
    $routes->get('page/users/bootstrap', '\App\Controllers\UserRoleController::bootstrap');
    $routes->get('page/products/bootstrap', '\App\Controllers\ProductPageController::bootstrap');
    $routes->get('page/inventory/bootstrap', '\App\Controllers\InventoryPageController::bootstrap');
    $routes->get('page/finance/bootstrap', '\App\Controllers\FinancePageController::bootstrap');
    $routes->get('setting', 'SettingsController::getGeneral');
    $routes->put('setting', 'SettingsController::general');
    $routes->get('printer', 'SettingsController::listPrinters');
    $routes->get('dining-table', 'SettingsController::listDiningTables');
    $routes->get('dining-table/(:segment)', 'SettingsController::getDiningTable/$1');
    $routes->post('dining-table', 'SettingsController::diningTable');
    $routes->put('dining-table/(:segment)', 'SettingsController::updateDiningTable/$1');
    $routes->delete('dining-table/(:segment)', 'SettingsController::deleteDiningTable/$1');
    $routes->get('payment-method', 'SettingsController::listPaymentMethods');
    $routes->get('payment-method/(:segment)', 'SettingsController::getPaymentMethod/$1');
    $routes->post('payment-method', 'SettingsController::paymentMethod');
    $routes->put('payment-method/(:segment)', 'SettingsController::updatePaymentMethod/$1');
    $routes->delete('payment-method/(:segment)', 'SettingsController::deletePaymentMethod/$1');
    $routes->post('payment-method-qris-image', 'SettingsController::uploadQrisImage');
    $routes->get('packaging-rule', 'SettingsController::listPackagingRules');
    $routes->get('packaging-rule/(:segment)', 'SettingsController::getPackagingRule/$1');
    $routes->post('packaging-rule', 'SettingsController::packagingRule');
    $routes->put('packaging-rule/(:segment)', 'SettingsController::updatePackagingRule/$1');
    $routes->delete('packaging-rule/(:segment)', 'SettingsController::deletePackagingRule/$1');
    $routes->get('reports/profit-loss', 'ReportController::profitLoss');
    $routes->get('finance/expense', 'ReportController::listOperatingExpenses');
    $routes->post('finance/expense', 'ReportController::operatingExpense');
    $routes->put('finance/expense/(:segment)', 'ReportController::updateOperatingExpense/$1');
    $routes->delete('finance/expense/(:segment)', 'ReportController::deleteOperatingExpense/$1');
    $routes->get('ingredient-template', 'InventoryController::listIngredientTemplates');
    $routes->post('ingredient-template', 'InventoryController::ingredientTemplate');
    $routes->put('ingredient-template/(:segment)', 'InventoryController::updateIngredientTemplate/$1');
    $routes->delete('ingredient-template/(:segment)', 'InventoryController::deleteIngredientTemplate/$1');
    $routes->get('ingredient', 'InventoryController::listIngredients');
    $routes->get('ingredient/(:segment)', 'InventoryController::getIngredient/$1');
    $routes->post('ingredient', 'InventoryController::ingredient');
    $routes->put('ingredient/(:segment)', 'InventoryController::updateIngredient/$1');
    $routes->delete('ingredient/(:segment)', 'InventoryController::deleteIngredient/$1');
    $routes->put('ingredient-mapping', 'InventoryController::ingredientMapping');
    $routes->get('stock-movement', 'InventoryController::listMovements');
    $routes->post('purchase', 'InventoryController::purchase');
    $routes->post('inventory-loss', 'InventoryController::waste');
    $routes->get('category', 'ProductSuiteController::listCategories');
    $routes->get('category/(:segment)', 'ProductSuiteController::getCategory/$1');
    $routes->post('category', 'ProductSuiteController::category');
    $routes->put('category/(:segment)', 'ProductSuiteController::updateCategory/$1');
    $routes->delete('category/(:segment)', 'ProductSuiteController::deleteCategory/$1');
    $routes->get('product', 'ProductSuiteController::listProducts');
    $routes->get('product/(:segment)', 'ProductSuiteController::getProduct/$1');
    $routes->post('product', 'ProductSuiteController::product');
    $routes->post('product/(:segment)/produce', 'ProductSuiteController::produceProduct/$1');
    $routes->post('product-batch/(:segment)/loss', 'ProductSuiteController::productBatchLoss/$1');
    $routes->put('product/(:segment)/price', 'ProductSuiteController::updateProductPrice/$1');
    $routes->put('product/(:segment)/category', 'ProductSuiteController::updateProductCategory/$1');
    $routes->delete('product/(:segment)/category', 'ProductSuiteController::deleteProductCategory/$1');
    $routes->put('product/(:segment)', 'ProductSuiteController::updateProduct/$1');
    $routes->delete('product/(:segment)', 'ProductSuiteController::deleteProduct/$1');
    $routes->get('modifier', 'ProductSuiteController::listModifiers');
    $routes->get('modifier/(:segment)', 'ProductSuiteController::getModifier/$1');
    $routes->post('modifier', 'ProductSuiteController::modifier');
    $routes->put('modifier/(:segment)/option-price', 'ProductSuiteController::updateModifierOptionPrice/$1');
    $routes->put('modifier/(:segment)', 'ProductSuiteController::updateModifier/$1');
    $routes->delete('modifier/(:segment)', 'ProductSuiteController::deleteModifier/$1');
    $routes->get('recipe', 'ProductSuiteController::listRecipes');
    $routes->post('recipe', 'ProductSuiteController::recipeLine');
    $routes->post('product-modifier', 'ProductSuiteController::productModifiers');
    $routes->post('product-image', 'ProductSuiteController::uploadProductImage');
    $routes->get('order', 'SalesController::listOrders');
    $routes->get('order/(:segment)', 'SalesController::getOrder/$1');
    $routes->post('order', 'SalesController::order');
    $routes->put('order/(:segment)', 'SalesController::updateOrder/$1');
    $routes->put('order/(:segment)/status', 'SalesController::status/$1');
    $routes->put('order/(:segment)/ready-items', 'SalesController::readyItems/$1');
    $routes->put('order/(:segment)/settle', 'SalesController::settle/$1');
    $routes->put('order/(:segment)/approve', 'SalesController::approve/$1');
    $routes->put('order/(:segment)/move-table', 'SalesController::moveTable/$1');
    $routes->post('payment-transaction', 'SalesController::createPayment');
    $routes->get('payment-gateway-log', 'SalesController::paymentLogs');
    $routes->get('payment-transaction/(:segment)', 'SalesController::paymentStatus/$1');
    $routes->put('payment-transaction/(:segment)/confirm', 'SalesController::confirmPayment/$1');
    $routes->put('payment-transaction/(:segment)/cancel', 'SalesController::cancelPayment/$1');
});

$routes->get('(:segment)', 'AppPageController::tenantDashboard/$1');
$routes->get('(:segment)/login', 'LoginController::tenant/$1');
$routes->get('(:segment)/login.html', 'LoginController::tenant/$1');
$routes->get('(:segment)/order', 'OnlineOrderController::tenant/$1');
$routes->get('(:segment)/index.html', 'AppPageController::tenantDashboard/$1');
$routes->get('(:segment)/pages/pos.html', 'PosController::tenant/$1');
$routes->get('(:segment)/pages/settings.html', 'SettingsPageController::tenant/$1');
$routes->get('(:segment)/pages/users.html', 'UserRoleController::tenant/$1');
$routes->get('(:segment)/pages/categories.html', 'ProductPageController::tenant/$1/categories');
$routes->get('(:segment)/pages/products.html', 'ProductPageController::tenant/$1/products');
$routes->get('(:segment)/pages/modifiers.html', 'ProductPageController::tenant/$1/modifiers');
$routes->get('(:segment)/pages/recipes.html', 'ProductPageController::tenant/$1/recipes');
$routes->get('(:segment)/pages/ingredient-mapping.html', 'ProductPageController::tenant/$1/ingredient-mapping');
$routes->get('(:segment)/pages/ingredient-templates.html', 'ProductPageController::tenant/$1/ingredient-templates');
$routes->get('(:segment)/pages/inventory.html', 'InventoryPageController::tenant/$1/overview');
$routes->get('(:segment)/pages/inventory-list.html', 'InventoryPageController::tenant/$1/list');
$routes->get('(:segment)/pages/purchases.html', 'InventoryPageController::tenant/$1/purchase');
$routes->get('(:segment)/pages/finished-products.html', 'InventoryPageController::tenant/$1/finished-products');
$routes->get('(:segment)/pages/finance-dashboard.html', 'FinancePageController::tenant/$1/dashboard');
$routes->get('(:segment)/pages/reports.html', 'FinancePageController::tenant/$1/profit-loss');
$routes->get('(:segment)/pages/finance-expenses.html', 'FinancePageController::tenant/$1/expenses');
$routes->get('(:segment)/pages/finance-settlement.html', 'FinancePageController::tenant/$1/settlement');
$routes->get('(:segment)/pages/payment-gateway-logs.html', 'FinancePageController::tenant/$1/gateway-logs');
$routes->get('(:segment)/pages/onboarding.html', 'AppPageController::tenantPage/$1/onboarding.html');
$routes->get('(:segment)/pages/order-history.html', 'AppPageController::tenantPage/$1/order-history.html');
$routes->get('pages/pos.html', 'PosController::show');
$routes->get('pages/settings.html', 'SettingsPageController::show');
$routes->get('pages/users.html', 'UserRoleController::show');
$routes->get('pages/categories.html', 'ProductPageController::show/categories');
$routes->get('pages/products.html', 'ProductPageController::show/products');
$routes->get('pages/modifiers.html', 'ProductPageController::show/modifiers');
$routes->get('pages/recipes.html', 'ProductPageController::show/recipes');
$routes->get('pages/ingredient-mapping.html', 'ProductPageController::show/ingredient-mapping');
$routes->get('pages/ingredient-templates.html', 'ProductPageController::show/ingredient-templates');
$routes->get('pages/inventory.html', 'InventoryPageController::show/overview');
$routes->get('pages/inventory-list.html', 'InventoryPageController::show/list');
$routes->get('pages/purchases.html', 'InventoryPageController::show/purchase');
$routes->get('pages/finished-products.html', 'InventoryPageController::show/finished-products');
$routes->get('pages/finance-dashboard.html', 'FinancePageController::show/dashboard');
$routes->get('pages/reports.html', 'FinancePageController::show/profit-loss');
$routes->get('pages/finance-expenses.html', 'FinancePageController::show/expenses');
$routes->get('pages/finance-settlement.html', 'FinancePageController::show/settlement');
$routes->get('pages/payment-gateway-logs.html', 'FinancePageController::show/gateway-logs');
$routes->get('pages/onboarding.html', 'AppPageController::page/onboarding.html');
$routes->get('pages/order-history.html', 'AppPageController::page/order-history.html');
$routes->get('(:segment)/pages/(:any)', 'AppPageController::tenantPage/$1/$2');
